# Generated by Django 6.0.7 on 2026-09-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('ann_type', models.CharField(choices=[('new', '资源上新'), ('script', '脚本更新'), ('note', '优质笔记'), ('tool', '工具更新')], default='new', max_length=20, verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='图片')),
                ('link', models.URLField(blank=True, verbose_name='链接')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档名称')),
                ('doc_type', models.CharField(choices=[('docx', 'Word文档'), ('pdf', 'PDF文档')], default='pdf', max_length=10, verbose_name='文档类型')),
                ('file', models.FileField(upload_to='knowledge/', verbose_name='文件')),
                ('summary', models.TextField(blank=True, verbose_name='简介摘要')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('tag', models.CharField(choices=[('tech', '技术'), ('office', '办公'), ('tool', '工具'), ('life', '生活'), ('other', '其他')], default='tech', max_length=20, verbose_name='分类标签')),
                ('content', models.TextField(verbose_name='内容')),
                ('intro', models.TextField(blank=True, verbose_name='简短导读')),
                ('author', models.CharField(default='管理员', max_length=50, verbose_name='作者')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='脚本名称')),
                ('scene', models.CharField(max_length=200, verbose_name='适用场景')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本号')),
                ('file', models.FileField(upload_to='scripts/', verbose_name='脚本文件')),
                ('tutorial', models.TextField(blank=True, verbose_name='使用教程')),
                ('downloads', models.IntegerField(default=0, verbose_name='下载次数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工具名称')),
                ('url', models.URLField(verbose_name='官网地址')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='简介')),
                ('category', models.CharField(choices=[('search', '搜索工具'), ('ai', 'AI工具'), ('dev', '开发工具'), ('design', '设计工具'), ('ops', '运维工具'), ('convert', '在线转换'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新增')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'ordering': ['-is_hot', '-created_at'],
            },
        ),
    ]
